# Generated by Django 5.1 on 2025-02-03 21:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='codigos_qr/')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='simulacionSap.estado')),
                ('id_tipo_equipo', models.ForeignKey(db_column='id_tipo_equipo', on_delete=django.db.models.deletion.CASCADE, to='simulacionSap.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id_reparacion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(default=datetime.date.today)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='simulacionSap.equipo')),
            ],
        ),
    ]
