# Generated by Django 5.1 on 2025-02-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulacionSap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='codigo_qr',
        ),
    ]
